image: atlassian/default-image:2

pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to Production
          script:
            - pipe: atlassian/ftp-deploy:0.7.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: /home/smartcrm/public_html/test.smartcrm.ws