image: atlassian/default-image:2

pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - pipe: atlassian/ftp-deploy:0.7.0
              variables:
                USER: crmTest@test.smartcrm.ws
                PASSWORD: HVmc3[?eP9lU
                SERVER: ftp.smartcrm.ws
                REMOTE_PATH: /public_html
                DELETE_FLAG: 'false' # Don't delete existing files
                EXTRA_ARGS: "--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore" # Ignore these