image: php:7.3

pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to Production
          script:
            - pipe: atlassian/ftp-deploy:0.7.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: /public_html/TestBackEndLaravelApi
                DELETE_FLAG: 'false' # Don't delete existing files
                EXTRA_ARGS: "--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore --exclude=storage/ --exclude=public/ --exclude=vendor/ --exclude=resources/"
