image: atlassian/default-image:2

pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - pipe: atlassian/ftp-deploy:0.7.0
              variables:
                USER: smartcrm@test.smartcrm.ws
                PASSWORD: 03B!@*g7K2M!
                SERVER: ftp.smartcrm.ws
                PORT: 21
                REMOTE_PATH: /home/smartcrm/public_html/test.smartcrm.ws/smartcrm
                DELETE_FLAG: 'false' # Don't delete existing files
                EXTRA_ARGS: "--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore" # Ignore these