image: php:7.3
pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to matgr.smartlifesys.online FTP
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD --host $FTP_HOST