image: php:7.3
pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to matgr.smartlifesys.online FTP
          script:
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://ftp.smartcrm.ws/public_html/TestBackEndLaravelApi