image: atlassian/default-image:2

pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to Production
          script:
            - apt-get update && apt-get install -y lftp
            - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rnev --exclude-glob .git --exclude-glob bitbucket-pipelines.yml --exclude-glob .gitignore . /public_html/TestBackEndLaravelApi"