image: php:7.3

pipelines:
  branches:
    test_masterBitbucket:
      - step:
          name: Deploy to matgr.smartlifesys.online FTP
          script:
            - export USER=$FTP_USERNAME
            - export PASSWORD=$FTP_PASSWORD
            - export SERVER=$FTP_HOST
            - export REMOTE_PATH=/public_html/TestBackEndLaravelApi
            - apt-get update
            - apt-get -qq install git-ftp
            - echo ".bitbucket/" > .git-ftp-ignore
            - echo ".git/" >> .git-ftp-ignore
            - echo "bitbucket-pipelines.yml" >> .git-ftp-ignore
            - echo ".gitignore" >> .git-ftp-ignore
            - echo "storage/" >> .git-ftp-ignore
            - echo "public/" >> .git-ftp-ignore
            - echo "vendor/" >> .git-ftp-ignore
            - echo "resources/" >> .git-ftp-ignore
            - git ftp push --user $USER --passwd $PASSWORD ftp://$SERVER$REMOTE_PATH